name: React On PR
on: [pull_request, workflow_dispatch]

jobs:
    checkout_repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install packages
              run: npm install 

            - name: Use custom action
              uses: ./pr_react 