name: React On PR
on: [pull_request, workflow_dispatch]

jobs:
    checkout_repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install packages
              run: npm install 

            - name: Use custom action
              uses: ./.github/actions/pr_react
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                pr_number: ${{ github.event.pull_request.number }}